version: "3.9"

services:
  mongo:
    image: mongo
    container_name: atlas-mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: atlas-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  user-service:
    build: ./apps/user-service
    container_name: user-service
    ports:
      - "4000:4000"
    env_file:
      - ./apps/user-service/.env
    depends_on:
      - mongo

  order-service:
    build: ./apps/order-service
    container_name: order-service
    ports:
      - "5000:5000"
    env_file:
      - ./apps/order-service/.env
    depends_on:
      - postgres

  frontend:
    build: ./apps/frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - order-service
